//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutbolPlayAdmin.Resources.Values {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FutbolPlayAdmin.Resources.Values.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports Play Coach.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar contraseña.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Reserva.
        /// </summary>
        internal static string change_status {
            get {
                return ResourceManager.GetString("change_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado se cambió correctamente.
        /// </summary>
        internal static string change_status_ok {
            get {
                return ResourceManager.GetString("change_status_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actual.
        /// </summary>
        internal static string current_password {
            get {
                return ResourceManager.GetString("current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realizar Reserva.
        /// </summary>
        internal static string do_reservation {
            get {
                return ResourceManager.GetString("do_reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario y/o password son incorrectos.
        /// </summary>
        internal static string error_code_003 {
            get {
                return ResourceManager.GetString("error_code_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con ese correo.
        /// </summary>
        internal static string error_code_004 {
            get {
                return ResourceManager.GetString("error_code_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo ingresado no existe.
        /// </summary>
        internal static string error_code_008 {
            get {
                return ResourceManager.GetString("error_code_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un problema al recuperar contraseña, por favor vuelve a intentarlo.
        /// </summary>
        internal static string error_code_009 {
            get {
                return ResourceManager.GetString("error_code_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual es incorrecta.
        /// </summary>
        internal static string error_code_012 {
            get {
                return ResourceManager.GetString("error_code_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un problema al conectarse con la aplicación.
        /// </summary>
        internal static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó la contraseña?.
        /// </summary>
        internal static string forgot_password {
            get {
                return ResourceManager.GetString("forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo Precio ....
        /// </summary>
        internal static string getting_price {
            get {
                return ResourceManager.GetString("getting_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener el precio.
        /// </summary>
        internal static string getting_price_error {
            get {
                return ResourceManager.GetString("getting_price_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando Sports Play Coach....
        /// </summary>
        internal static string loading_app {
            get {
                return ResourceManager.GetString("loading_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Sesión.
        /// </summary>
        internal static string log_off {
            get {
                return ResourceManager.GetString("log_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo no es válido.
        /// </summary>
        internal static string mail_error {
            get {
                return ResourceManager.GetString("mail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Perfil.
        /// </summary>
        internal static string my_profile {
            get {
                return ResourceManager.GetString("my_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva contraseña (mínimo 6 caracteres).
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario de atención.
        /// </summary>
        internal static string opening_hours {
            get {
                return ResourceManager.GetString("opening_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se cambio la contraseña correctamente.
        /// </summary>
        internal static string password_changed {
            get {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contaseñas deben ser iguales.
        /// </summary>
        internal static string password_differents_message {
            get {
                return ResourceManager.GetString("password_differents_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El celular no es válido.
        /// </summary>
        internal static string phone_error {
            get {
                return ResourceManager.GetString("phone_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancha.
        /// </summary>
        internal static string pitch_prefix_length {
            get {
                return ResourceManager.GetString("pitch_prefix_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string pitch_prefix_short {
            get {
                return ResourceManager.GetString("pitch_prefix_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canchas Normales.
        /// </summary>
        internal static string programation {
            get {
                return ResourceManager.GetString("programation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canchas Múltiples.
        /// </summary>
        internal static string programation_multiple {
            get {
                return ResourceManager.GetString("programation_multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese de nuevo la nueva contraseña.
        /// </summary>
        internal static string re_password {
            get {
                return ResourceManager.GetString("re_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se envió un correo para recuperar la contraseña.
        /// </summary>
        internal static string recover_password_message {
            get {
                return ResourceManager.GetString("recover_password_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar contraseña.
        /// </summary>
        internal static string remember_password {
            get {
                return ResourceManager.GetString("remember_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada por el establecimiento.
        /// </summary>
        internal static string reservation_cancel_place_short {
            get {
                return ResourceManager.GetString("reservation_cancel_place_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú la cancelaste.
        /// </summary>
        internal static string reservation_cancel_user_short {
            get {
                return ResourceManager.GetString("reservation_cancel_user_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada.
        /// </summary>
        internal static string reservation_close_short {
            get {
                return ResourceManager.GetString("reservation_close_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La reserva que intentas realizar ya no está disponible.
        /// </summary>
        internal static string reservation_conflict {
            get {
                return ResourceManager.GetString("reservation_conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La reserva se realizó correctamente.
        /// </summary>
        internal static string reservation_ok {
            get {
                return ResourceManager.GetString("reservation_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmada.
        /// </summary>
        internal static string reservation_ok_short {
            get {
                return ResourceManager.GetString("reservation_ok_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu reserva se realizó, en unos minutos te estará llamando un representante de la cancha para confirmarte la reserva.
        /// </summary>
        internal static string reservation_pending {
            get {
                return ResourceManager.GetString("reservation_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente por confirmar.
        /// </summary>
        internal static string reservation_pending_short {
            get {
                return ResourceManager.GetString("reservation_pending_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendientes por confirmar.
        /// </summary>
        internal static string reservation_pending_title {
            get {
                return ResourceManager.GetString("reservation_pending_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes reservas pendientes por confirmar.
        /// </summary>
        internal static string reservation_pending_to_confirm {
            get {
                return ResourceManager.GetString("reservation_pending_to_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugando.
        /// </summary>
        internal static string reservation_running_short {
            get {
                return ResourceManager.GetString("reservation_running_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        internal static string reservation_text1 {
            get {
                return ResourceManager.GetString("reservation_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha y hora:.
        /// </summary>
        internal static string reservation_text2 {
            get {
                return ResourceManager.GetString("reservation_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado actual:.
        /// </summary>
        internal static string reservation_text3 {
            get {
                return ResourceManager.GetString("reservation_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor es:.
        /// </summary>
        internal static string reservation_text4 {
            get {
                return ResourceManager.GetString("reservation_text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancha:.
        /// </summary>
        internal static string reservation_text5 {
            get {
                return ResourceManager.GetString("reservation_text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea guardar la reserva con el valor: {0}?.
        /// </summary>
        internal static string reservation_with_price_zero {
            get {
                return ResourceManager.GetString("reservation_with_price_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintentar.
        /// </summary>
        internal static string retry {
            get {
                return ResourceManager.GetString("retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró ningún usuario con ese nombre.
        /// </summary>
        internal static string search_without_data {
            get {
                return ResourceManager.GetString("search_without_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelada.
        /// </summary>
        internal static string status_cancel {
            get {
                return ResourceManager.GetString("status_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada.
        /// </summary>
        internal static string status_close {
            get {
                return ResourceManager.GetString("status_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobada.
        /// </summary>
        internal static string status_ok {
            get {
                return ResourceManager.GetString("status_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de Confirmar.
        /// </summary>
        internal static string status_pending {
            get {
                return ResourceManager.GetString("status_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entregada.
        /// </summary>
        internal static string status_running {
            get {
                return ResourceManager.GetString("status_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se actualizaron correctamente.
        /// </summary>
        internal static string update_profile_message {
            get {
                return ResourceManager.GetString("update_profile_message", resourceCulture);
            }
        }
    }
}
